// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdsvjdjdhwvjgkwbmyny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkc3ZqZGpkaHd2amdrd2JteW55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjMzNDgsImV4cCI6MjA2ODgzOTM0OH0.QQhsS3lxjCO-YyULrt1GgzEDr0knQPJaIHcNhPq4zUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});